/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controle.ControleAlteraPrato;
import Entidade.Pessoa;
import Entidade.Prato;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Samsung
 */
public class TelaAlterarPrato extends javax.swing.JFrame {
    private ArrayList erro = new ArrayList();
    private String nome;
    private String login;
    private String senha;
    private String perfil;
    
    private String nomeAltera;
    private String descricaoAltera;
    private String categoriaAltera;
    private float precoAltera;
    /**
     * Creates new form TelaAlterarPrato
     */
    public TelaAlterarPrato(Pessoa p, Prato pr) {
        initComponents();
        nome = p.getNomePessoa();
        login = p.getLoginPessoa();
        senha = p.getSenhaPessoa();
        perfil = p.getPerfilPessoa();
        
        jTextFieldNomePrato.setText(pr.getNomePrato());
        jTextFieldDescricao.setText(pr.getDescricaoPrato());
        jComboBoxCategoria.setSelectedItem(pr.getCategoriaPrato());
        jTextFieldPrecoPrato.setText(String.valueOf(pr.getPrecoPrato()));
        
        nomeAltera = pr.getNomePrato();
        descricaoAltera = pr.getDescricaoPrato();
        categoriaAltera = pr.getCategoriaPrato();
        precoAltera = pr.getPrecoPrato();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        NomePrato = new javax.swing.JLabel();
        jButtonAtualizar = new javax.swing.JButton();
        Categoria = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jTextFieldPrecoPrato = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        Preco = new javax.swing.JLabel();
        Descricao = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jTextFieldNomePrato = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/perfeito.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 430, 110, 60));

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png"))); // NOI18N
        jButtonVoltar.setBorder(null);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseExited(evt);
            }
        });
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 200, 40));

        NomePrato.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        NomePrato.setForeground(new java.awt.Color(255, 255, 255));
        NomePrato.setText("Nome Prato:");
        getContentPane().add(NomePrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ATUALIZAR.png"))); // NOI18N
        jButtonAtualizar.setBorder(null);
        jButtonAtualizar.setContentAreaFilled(false);
        jButtonAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAtualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAtualizarMouseExited(evt);
            }
        });
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 200, 40));

        Categoria.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Categoria.setForeground(new java.awt.Color(255, 255, 255));
        Categoria.setText("Categoria:");
        getContentPane().add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        Titulo.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("ATUALIZAR PRATO");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 160, -1));

        jTextFieldPrecoPrato.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldPrecoPrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 350, 30));

        jTextFieldDescricao.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 350, 30));

        Preco.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Preco.setForeground(new java.awt.Color(255, 255, 255));
        Preco.setText("Preço:");
        getContentPane().add(Preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        Descricao.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Descricao.setForeground(new java.awt.Color(255, 255, 255));
        Descricao.setText("Descrição:");
        getContentPane().add(Descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jComboBoxCategoria.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Tradicional", "Especiais" }));
        getContentPane().add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 350, 30));

        jTextFieldNomePrato.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldNomePrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 350, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TAMANHO CERTO.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaAdministrador(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldNomePrato.getText();
        String categoria = String.valueOf(jComboBoxCategoria.getSelectedItem());
        String descricao = jTextFieldDescricao.getText();
        float preco = Float.valueOf(jTextFieldPrecoPrato.getText());

        Prato pr = new Prato(null, nomeAltera, categoriaAltera, descricaoAltera, precoAltera);
        //System.err.println(pr);
        pr = Modelos.ModelPrato.getInstance().obterPratoPesquisa(pr);
        Prato pr1 = new Prato(pr.getCodigoPrato(),nome, categoria, descricao, preco);
        Controle.ControleAlteraPrato Controle = new ControleAlteraPrato();

        try {
            erro = Controle.validaAltDadosPrato(pr1);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaAlterarPrato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonAtualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtualizarMouseEntered
        // TODO add your handling code here:
        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ATUALIZAR 2.png")));
    }//GEN-LAST:event_jButtonAtualizarMouseEntered

    private void jButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseEntered
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR 2.png")));
    }//GEN-LAST:event_jButtonVoltarMouseEntered

    private void jButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseExited
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png")));
    }//GEN-LAST:event_jButtonVoltarMouseExited

    private void jButtonAtualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtualizarMouseExited
        // TODO add your handling code here:
        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ATUALIZAR.png")));
    }//GEN-LAST:event_jButtonAtualizarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new TelaAlterarPrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel Descricao;
    private javax.swing.JLabel NomePrato;
    private javax.swing.JLabel Preco;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldNomePrato;
    private javax.swing.JTextField jTextFieldPrecoPrato;
    // End of variables declaration//GEN-END:variables
}
