/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controle.ControleAlterarBebida;
import Entidade.Bebida;
import Entidade.Pessoa;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Samsung
 */
public class TelaAlterarBebida extends javax.swing.JFrame {
    private ArrayList erro = new ArrayList();
    private String nome;
    private String login;
    private String senha;
    private String perfil;
    
    private String nomeAltera;
    private String descricaoAltera;
    private String categoriaAltera;
    private String tamanhoAltera;
    private float precoAltera;
    /**
     * Creates new form TelaAlterarBebida
     */
    public TelaAlterarBebida(Pessoa p, Bebida b) {
        initComponents();
        nome = p.getNomePessoa();
        login = p.getLoginPessoa();
        senha = p.getSenhaPessoa();
        perfil = p.getPerfilPessoa();
        
        jTextFieldNomeBebida.setText(b.getNomeBebida());
        jTextFieldDescricaoBebida.setText(b.getDescricaoBebida());
        jComboBoxCategoria.setSelectedItem(b.getCategoriaBebida());
        jTextFieldTamanho.setText(b.getTamanhoBebida());
        jTextFieldPreco.setText(String.valueOf(b.getPrecoBebida()));
        
        nomeAltera = b.getNomeBebida();
        descricaoAltera = b.getDescricaoBebida();
        categoriaAltera = b.getCategoriaBebida();
        tamanhoAltera = b.getTamanhoBebida();
        precoAltera = b.getPrecoBebida();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldPreco = new javax.swing.JTextField();
        Preco = new javax.swing.JLabel();
        jButtonInserir = new javax.swing.JButton();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldDescricaoBebida = new javax.swing.JTextField();
        DescricaoBebida = new javax.swing.JLabel();
        jTextFieldNomeBebida = new javax.swing.JTextField();
        NomeBebida = new javax.swing.JLabel();
        Categoria = new javax.swing.JLabel();
        Tamanho = new javax.swing.JLabel();
        jTextFieldTamanho = new javax.swing.JTextField();
        jButton1Voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/perfeito.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 100, 70));

        jTextFieldPreco.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 400, 30));

        Preco.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Preco.setForeground(new java.awt.Color(255, 255, 255));
        Preco.setText("Preço:");
        getContentPane().add(Preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jButtonInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO INSERIR.png"))); // NOI18N
        jButtonInserir.setBorder(null);
        jButtonInserir.setContentAreaFilled(false);
        jButtonInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonInserirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonInserirMouseExited(evt);
            }
        });
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 200, 40));

        jComboBoxCategoria.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Vinhos", "Sucos", "Refrigerantes" }));
        getContentPane().add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 400, 30));

        jLabelTitulo.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("ALTERAR BEBIDA");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 160, -1));

        jTextFieldDescricaoBebida.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldDescricaoBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 400, 30));

        DescricaoBebida.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        DescricaoBebida.setForeground(new java.awt.Color(255, 255, 255));
        DescricaoBebida.setText("Descrição:");
        getContentPane().add(DescricaoBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jTextFieldNomeBebida.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldNomeBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 400, 30));

        NomeBebida.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        NomeBebida.setForeground(new java.awt.Color(255, 255, 255));
        NomeBebida.setText("Nome Bebida:");
        getContentPane().add(NomeBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        Categoria.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Categoria.setForeground(new java.awt.Color(255, 255, 255));
        Categoria.setText("Categoria:");
        getContentPane().add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        Tamanho.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Tamanho.setForeground(new java.awt.Color(255, 255, 255));
        Tamanho.setText("Tamanho:");
        getContentPane().add(Tamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jTextFieldTamanho.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jTextFieldTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTamanhoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 400, 30));

        jButton1Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png"))); // NOI18N
        jButton1Voltar.setBorder(null);
        jButton1Voltar.setContentAreaFilled(false);
        jButton1Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1VoltarMouseExited(evt);
            }
        });
        jButton1Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sucos.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldNomeBebida.getText();
        String descricao = jTextFieldDescricaoBebida.getText();
        String categoria = String.valueOf(jComboBoxCategoria.getSelectedItem());
        String tamanho = jTextFieldTamanho.getText();
        float preco = Float.valueOf(jTextFieldPreco.getText());

        Bebida b = new Bebida(null,nomeAltera,descricaoAltera,categoriaAltera,tamanhoAltera,precoAltera);
        b = Modelos.ModelBebida.getInstance().obterBebidaPesquisa(b);
        Bebida br1 = new Bebida(b.getCodigoBebida(),nome, categoria, descricao,tamanho, preco);
        Controle.ControleAlterarBebida Controle = new ControleAlterarBebida();
        
        try {
            erro = Controle.validaAltDadosBebida(br1);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaAlterarBebida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jTextFieldTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTamanhoActionPerformed

    private void jButtonInserirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInserirMouseEntered
        // TODO add your handling code here:
        jButtonInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO INSERIR 2.png")));
    }//GEN-LAST:event_jButtonInserirMouseEntered

    private void jButtonInserirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInserirMouseExited
        // TODO add your handling code here:
        jButtonInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO INSERIR.png")));
    }//GEN-LAST:event_jButtonInserirMouseExited

    private void jButton1VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1VoltarMouseEntered
        // TODO add your handling code here:
        jButton1Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR 2.png")));
    }//GEN-LAST:event_jButton1VoltarMouseEntered

    private void jButton1VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1VoltarMouseExited
        // TODO add your handling code here:
        jButton1Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png")));
    }//GEN-LAST:event_jButton1VoltarMouseExited

    private void jButton1VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1VoltarActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaAdministrador(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new TelaAlterarBebida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel DescricaoBebida;
    private javax.swing.JLabel NomeBebida;
    private javax.swing.JLabel Preco;
    private javax.swing.JLabel Tamanho;
    private javax.swing.JButton jButton1Voltar;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldDescricaoBebida;
    private javax.swing.JTextField jTextFieldNomeBebida;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldTamanho;
    // End of variables declaration//GEN-END:variables
}
