/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controle.ControleInserirPrato;
import Entidade.Pessoa;
import Entidade.Prato;
import java.util.ArrayList;

/**
 *
 * @author Samsung
 */
public class TelaCadastroPrato extends javax.swing.JFrame {
private ArrayList erro = new ArrayList();
    private String nome;
    private String login;
    private String senha;
    private String perfil;
   
    /**
     * Creates new form TelaCadastroBebida
     */
    public TelaCadastroPrato(Pessoa p) {
        initComponents();
        nome = p.getNomePessoa();
        login = p.getLoginPessoa();
        senha = p.getSenhaPessoa();
        perfil = p.getPerfilPessoa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Descricao = new javax.swing.JLabel();
        jTextFieldNomePrato = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        NomePrato = new javax.swing.JLabel();
        jButtonInserirPrato = new javax.swing.JButton();
        Categoria = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jTextFieldPrecoPrato = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        Preco = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/perfeito.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 440, 120, 60));

        Descricao.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Descricao.setForeground(new java.awt.Color(255, 255, 255));
        Descricao.setText("Descrição:");
        getContentPane().add(Descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 130, -1));

        jTextFieldNomePrato.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldNomePrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 390, 30));

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png"))); // NOI18N
        jButtonVoltar.setBorder(null);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseExited(evt);
            }
        });
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 200, 40));

        NomePrato.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        NomePrato.setForeground(new java.awt.Color(255, 255, 255));
        NomePrato.setText("Nome Prato:");
        getContentPane().add(NomePrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 140, -1));

        jButtonInserirPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO INSERIR.png"))); // NOI18N
        jButtonInserirPrato.setBorder(null);
        jButtonInserirPrato.setContentAreaFilled(false);
        jButtonInserirPrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonInserirPratoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonInserirPratoMouseExited(evt);
            }
        });
        jButtonInserirPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirPratoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInserirPrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 200, 40));

        Categoria.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Categoria.setForeground(new java.awt.Color(255, 255, 255));
        Categoria.setText("Categoria:");
        getContentPane().add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 120, -1));

        Titulo.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("CADASTRAR NOVO PRATO");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 240, -1));

        jTextFieldPrecoPrato.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldPrecoPrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 390, 30));

        jTextFieldDescricao.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 390, 30));

        Preco.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Preco.setForeground(new java.awt.Color(255, 255, 255));
        Preco.setText("Preço:");
        getContentPane().add(Preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 100, -1));

        jComboBoxCategoria.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Tradicional", "Especiais" }));
        getContentPane().add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 390, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TAMANHO CERTO.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirPratoActionPerformed
               // TODO add your handling code here:
            String nome = jTextFieldNomePrato.getText();
            String categoria = String.valueOf(jComboBoxCategoria.getSelectedItem());
            String descricao = jTextFieldDescricao.getText();
            float preco = Float.valueOf(jTextFieldPrecoPrato.getText());
            
            Prato pr = new Prato(nome, categoria, descricao, preco);
        
            Controle.ControleInserirPrato Controle = new ControleInserirPrato();
            
            try {
                erro = Controle.validaDadosPrato(pr);
            } catch (ClassNotFoundException ex) {
                System.err.println("Catch!");
            }
    }//GEN-LAST:event_jButtonInserirPratoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaAdministrador(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonInserirPratoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInserirPratoMouseEntered
        // TODO add your handling code here:
        jButtonInserirPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO INSERIR 2.png")));
    }//GEN-LAST:event_jButtonInserirPratoMouseEntered

    private void jButtonInserirPratoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInserirPratoMouseExited
        // TODO add your handling code here:
        jButtonInserirPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO INSERIR.png")));
    }//GEN-LAST:event_jButtonInserirPratoMouseExited

    private void jButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseEntered
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR 2.png")));
    }//GEN-LAST:event_jButtonVoltarMouseEntered

    private void jButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseExited
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png")));
    }//GEN-LAST:event_jButtonVoltarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaCadastroPrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel Descricao;
    private javax.swing.JLabel NomePrato;
    private javax.swing.JLabel Preco;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButtonInserirPrato;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldNomePrato;
    private javax.swing.JTextField jTextFieldPrecoPrato;
    // End of variables declaration//GEN-END:variables
}
