/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Entidade.Bebida;
import Entidade.Pessoa;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samsung
 */
public class TelaBebida extends javax.swing.JFrame {
    private String nome;
    private String login;
    private String senha;
    private String perfil;
    private NumberFormat formatter = new DecimalFormat("0.00");
    /**
     * Creates new form TelaBebida
     */
    public TelaBebida(Pessoa p) {
        initComponents();
        nome = p.getNomePessoa();
        login = p.getLoginPessoa();
        senha = p.getSenhaPessoa();
        perfil = p.getPerfilPessoa();
        
        construirTabela();
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
    }
    
    private void construirTabela(){
    ArrayList<Bebida> lista = Modelos.ModelBebida.getInstance().obterListaBebida();
        
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Nome");
        modelo.addColumn("Descrição");
        modelo.addColumn("Categoria");
        modelo.addColumn("Tamanho");
        modelo.addColumn("Preço");

        if (lista.size() == 0) {
            modelo.addRow(new String[]{"Sem dados",
                        null,
                        null,
                        null,
                        null,});
        }
        
        for (int i = 0; i < lista.size(); i++) {
            Bebida b = lista.get(i);
            
//            System.out.println("Testando Lista: "+lista.get(i));
            //System.out.println(p.toString());
            // Alimenta as linhas de dados  
            modelo.addRow(new String[]{
                        b.getNomeBebida(),
                        b.getDescricaoBebida()+"",
                        b.getCategoriaBebida()+"",
                        b.getTamanhoBebida()+"",
                        "R$ "+formatter.format(b.getPrecoBebida())+ "",});
        }

        jTableBebidas.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBebidas = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButton1Voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableBebidas.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jTableBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Descricao", "Categoria", "Tamanho", "Preço"
            }
        ));
        jTableBebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBebidasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBebidas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 720, 410));

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO EDITAR.png"))); // NOI18N
        jButtonEditar.setBorder(null);
        jButtonEditar.setContentAreaFilled(false);
        jButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEditarMouseExited(evt);
            }
        });
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 200, 40));

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO EXCLUIR.png"))); // NOI18N
        jButtonExcluir.setBorder(null);
        jButtonExcluir.setContentAreaFilled(false);
        jButtonExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonExcluirMouseExited(evt);
            }
        });
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 200, 40));

        jButton1Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png"))); // NOI18N
        jButton1Voltar.setBorder(null);
        jButton1Voltar.setContentAreaFilled(false);
        jButton1Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1VoltarMouseExited(evt);
            }
        });
        jButton1Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sucos.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1VoltarActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaAdministrador(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1VoltarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int linha = jTableBebidas.getSelectedRow();
        Bebida b = Modelos.ModelBebida.getInstance().listaBebida().get(linha);
        try {
            Modelos.ModelBebida.getInstance().excluirBebida(b);
        } catch (SQLException ex) {
            Logger.getLogger(TelaBebida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaBebida.class.getName()).log(Level.SEVERE, null, ex);
        }
        Modelos.ModelBebida.getInstance().obterListaBebida();
        construirTabela();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        int linha = jTableBebidas.getSelectedRow();
        Pessoa p = new Pessoa (nome, login, perfil, senha);
        Bebida b = Modelos.ModelBebida.getInstance().listaBebida().get(linha);
        new TelaAlterarBebida(p,b).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButton1VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1VoltarMouseEntered
        // TODO add your handling code here:
        jButton1Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR 2.png")));
    }//GEN-LAST:event_jButton1VoltarMouseEntered

    private void jButton1VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1VoltarMouseExited
        // TODO add your handling code here:
        jButton1Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png")));
    }//GEN-LAST:event_jButton1VoltarMouseExited

    private void jButtonExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirMouseEntered
        // TODO add your handling code here:
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO EXCLUIR 2.png")));
    }//GEN-LAST:event_jButtonExcluirMouseEntered

    private void jButtonExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirMouseExited
        // TODO add your handling code here:
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO EXCLUIR.png")));
    }//GEN-LAST:event_jButtonExcluirMouseExited

    private void jButtonEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarMouseEntered
        // TODO add your handling code here:
         jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO EDITAR 2.png")));
    }//GEN-LAST:event_jButtonEditarMouseEntered

    private void jButtonEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarMouseExited
        // TODO add your handling code here:
         jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO EDITAR.png")));
    }//GEN-LAST:event_jButtonEditarMouseExited

    private void jTableBebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBebidasMouseClicked
        // TODO add your handling code here:
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jTableBebidasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaBebida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Voltar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBebidas;
    // End of variables declaration//GEN-END:variables
}
