/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Entidade.Pessoa;

/**
 *
 * @author AndrheiHenrique
 */
public class TelaGarcom extends javax.swing.JFrame {

    private String nome;
    private String login;
    private String senha;
    private String perfil;
    /**
     * Creates new form TelaGarcom
     */
    public TelaGarcom(Pessoa p) {
        initComponents();
        nome = p.getNomePessoa();
        login = p.getLoginPessoa();
        senha = p.getSenhaPessoa();
        perfil = p.getPerfilPessoa();
        
        jLabelNomeUsuario.setText(perfil+": "+nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jButtonVerMesas = new javax.swing.JButton();
        jButtonFazerPedido = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/GARÇOM 2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 130, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/perfeito.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 130, 60));

        jLabelNomeUsuario.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabelNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabelNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 310, 20));

        jButtonVerMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VER MESAS.png"))); // NOI18N
        jButtonVerMesas.setBorder(null);
        jButtonVerMesas.setContentAreaFilled(false);
        jButtonVerMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVerMesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVerMesasMouseExited(evt);
            }
        });
        jButtonVerMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerMesasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVerMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 200, 40));

        jButtonFazerPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO FAZER PEDIDO.png"))); // NOI18N
        jButtonFazerPedido.setBorder(null);
        jButtonFazerPedido.setContentAreaFilled(false);
        jButtonFazerPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonFazerPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonFazerPedidoMouseExited(evt);
            }
        });
        jButtonFazerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFazerPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFazerPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 200, 40));

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png"))); // NOI18N
        jButtonVoltar.setBorder(null);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseExited(evt);
            }
        });
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TAMANHO CERTO.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerMesasActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaMesa(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVerMesasActionPerformed

    private void jButtonFazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFazerPedidoActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        int mesa = 0;
        new TelaCadastroPedido(p, mesa).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonFazerPedidoActionPerformed

    private void jButtonVerMesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVerMesasMouseExited
        // TODO add your handling code here:
        jButtonVerMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VER MESAS.png")));
    }//GEN-LAST:event_jButtonVerMesasMouseExited

    private void jButtonVerMesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVerMesasMouseEntered
        // TODO add your handling code here:
        jButtonVerMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VER MESAS 2.png")));
    }//GEN-LAST:event_jButtonVerMesasMouseEntered

    private void jButtonFazerPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFazerPedidoMouseEntered
        // TODO add your handling code here:
        jButtonFazerPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO FAZER PEDIDO 2.png")));
    }//GEN-LAST:event_jButtonFazerPedidoMouseEntered

    private void jButtonFazerPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFazerPedidoMouseExited
        // TODO add your handling code here:
        jButtonFazerPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO FAZER PEDIDO.png")));
    }//GEN-LAST:event_jButtonFazerPedidoMouseExited

    private void jButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseEntered
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR 2.png")));
    }//GEN-LAST:event_jButtonVoltarMouseEntered

    private void jButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseExited
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png")));
    }//GEN-LAST:event_jButtonVoltarMouseExited

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGarcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGarcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGarcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGarcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new TelaGarcom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFazerPedido;
    private javax.swing.JButton jButtonVerMesas;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
