/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controle.ControlePedido;
import Entidade.Bebida;
import Entidade.Pedido;
import Entidade.Pessoa;
import Entidade.Prato;
import Entidade.Sobremesa;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndrheiHenrique
 */
public class TelaCadastroPedido extends javax.swing.JFrame {

    private ArrayList erro = new ArrayList();
    ArrayList<Pedido> listaPedido = new ArrayList();
    
    private int mesa;
    private String nome;
    private String login;
    private String senha;
    private String perfil;
    /**
     * Creates new form TelaCadastroPedido
     */
    public TelaCadastroPedido(Pessoa p, int mesa) {
        initComponents();
        if(mesa == 0){
            this.mesa = Integer.valueOf(JOptionPane.showInputDialog("Número da Mesa"));
        }else{
            this.mesa = mesa;
        }
        jLabelMesa.setText("Número da Mesa: "+String.valueOf(this.mesa));
        nome = p.getNomePessoa();
        login = p.getLoginPessoa();
        senha = p.getSenhaPessoa();
        perfil = p.getPerfilPessoa();
        construirTabelaBebida();
        construirTabelaPrato();
        construirTabelaSobremesa();
    }
    
    private void construirTabelaBebida(){
    ArrayList<Bebida> lista = Modelos.ModelBebida.getInstance().obterListaBebida();
        
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Nome");
        modelo.addColumn("Tamanho");
        modelo.addColumn("Preço");

        if (lista.size() == 0) {
            modelo.addRow(new String[]{"Sem dados",
                        null,
                        null,});
        }
        
        for (int i = 0; i < lista.size(); i++) {
            Bebida b = lista.get(i);
//             Alimenta as linhas de dados  
            modelo.addRow(new String[]{
                        b.getNomeBebida(),
                        b.getTamanhoBebida()+"",
                        b.getPrecoBebida()+ "",});
        }

        jTableBebida.setModel(modelo);
    }
    
    private void construirTabelaPrato(){
    ArrayList<Prato> lista = Modelos.ModelPrato.getInstance().obterListaPrato();
        
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Nome");
        modelo.addColumn("Preço");

        if (lista.size() == 0) {
            modelo.addRow(new String[]{"Sem dados",
                        null,});
        }
        
        for (int i = 0; i < lista.size(); i++) {
            Prato p = lista.get(i);
//             Alimenta as linhas de dados  
            modelo.addRow(new String[]{
                        p.getNomePrato(),
                        p.getPrecoPrato()+ "",});
        }

        jTablePrato.setModel(modelo);

    }

    private void construirTabelaSobremesa(){
    ArrayList<Sobremesa> lista = Modelos.ModelSobremesa.getInstance().obterListaSobremesa();
        
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Nome");
        modelo.addColumn("Preço");

        if (lista.size() == 0) {
            modelo.addRow(new String[]{"Sem dados",
                        null,});
        }
        
        for (int i = 0; i < lista.size(); i++) {
            Sobremesa s = lista.get(i);
//             Alimenta as linhas de dados 
            modelo.addRow(new String[]{
                        s.getNomeSobremesa(),
                        s.getPrecoSobremesa()+ "",});
        }

        jTableSobremesa.setModel(modelo);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAddPrato = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrato = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBebida = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSobremesa = new javax.swing.JTable();
        jButtonFinalizarPedido = new javax.swing.JButton();
        jButtonAddBebida = new javax.swing.JButton();
        jButtonAddSobremesa = new javax.swing.JButton();
        jLabelMesa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAddPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ADICIONAR.png"))); // NOI18N
        jButtonAddPrato.setBorder(null);
        jButtonAddPrato.setContentAreaFilled(false);
        jButtonAddPrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddPratoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddPratoMouseExited(evt);
            }
        });
        jButtonAddPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPratoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddPrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 200, 40));

        jTablePrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePrato);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 500, 140));

        jTableBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableBebida);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 500, 140));

        jTableSobremesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableSobremesa);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 500, 140));

        jButtonFinalizarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO FINALIZAR PEDIDO.png"))); // NOI18N
        jButtonFinalizarPedido.setBorder(null);
        jButtonFinalizarPedido.setContentAreaFilled(false);
        jButtonFinalizarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonFinalizarPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonFinalizarPedidoMouseExited(evt);
            }
        });
        jButtonFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFinalizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 200, 40));

        jButtonAddBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ADICIONAR.png"))); // NOI18N
        jButtonAddBebida.setBorder(null);
        jButtonAddBebida.setContentAreaFilled(false);
        jButtonAddBebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddBebidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddBebidaMouseExited(evt);
            }
        });
        jButtonAddBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBebidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 200, 40));

        jButtonAddSobremesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ADICIONAR.png"))); // NOI18N
        jButtonAddSobremesa.setBorder(null);
        jButtonAddSobremesa.setContentAreaFilled(false);
        jButtonAddSobremesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddSobremesaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddSobremesaMouseExited(evt);
            }
        });
        jButtonAddSobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSobremesaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddSobremesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 200, 40));

        jLabelMesa.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabelMesa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMesa.setText("Número Da Mesa:");
        getContentPane().add(jLabelMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 210, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TAMANHO CERTO.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarPedidoActionPerformed
        // TODO add your handling code here:       
        Pessoa p = new Pessoa (nome, login,perfil,senha);
        Controle.ControlePedido Controle = new ControlePedido();
        try {
            Controle.validaDadosPedido(listaPedido);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        listaPedido.clear();
        new TelaGarcom(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonFinalizarPedidoActionPerformed

    private void jButtonAddPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPratoActionPerformed
        // TODO add your handling code here:
        int linhaPrato = jTablePrato.getSelectedRow();
        String nomePedido = String.valueOf(jTablePrato.getValueAt(linhaPrato, 0));
        float precoPrato = Float.valueOf(String.valueOf(jTablePrato.getValueAt(linhaPrato, 1)));
        Pessoa p = new Pessoa (nome, login,senha,perfil);
        String nomeGarcom = p.getNomePessoa();
        
        Pedido pd = new Pedido(nomePedido, mesa, nomeGarcom, precoPrato, "", true, false);
        
        listaPedido.add(pd);
        JOptionPane.showMessageDialog(null, "Item adicionado ao pedido!");
    }//GEN-LAST:event_jButtonAddPratoActionPerformed

    private void jButtonAddBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBebidaActionPerformed
        // TODO add your handling code here:
        int linhaBebida = jTableBebida.getSelectedRow();
        String nomePedido = String.valueOf(jTableBebida.getValueAt(linhaBebida, 0));
        float precoPrato = Float.valueOf(String.valueOf(jTableBebida.getValueAt(linhaBebida, 2)));
        Pessoa p = new Pessoa (nome, login,senha,perfil);
        String nomeGarcom = p.getNomePessoa();
        String tamanho = String.valueOf(jTableBebida.getValueAt(linhaBebida, 1));
        
        Pedido pd = new Pedido(nomePedido, mesa, nomeGarcom, precoPrato, tamanho, true, false);  
        
        listaPedido.add(pd);
        JOptionPane.showMessageDialog(null, "Item adicionado ao pedido!");
    }//GEN-LAST:event_jButtonAddBebidaActionPerformed

    private void jButtonAddSobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSobremesaActionPerformed
        // TODO add your handling code here:
        int linhaSobremesa = jTableSobremesa.getSelectedRow();
        String nomePedido = String.valueOf(jTableSobremesa.getValueAt(linhaSobremesa, 0));
        float precoPrato = Float.valueOf(String.valueOf(jTableSobremesa.getValueAt(linhaSobremesa, 1)));
        Pessoa p = new Pessoa (nome, login,senha,perfil);
        String nomeGarcom = p.getNomePessoa();
        
        Pedido pd = new Pedido(nomePedido, mesa, nomeGarcom, precoPrato, "", true, false);
        
        listaPedido.add(pd);
        JOptionPane.showMessageDialog(null, "Item adicionado ao pedido!");
    }//GEN-LAST:event_jButtonAddSobremesaActionPerformed

    private void jButtonAddPratoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddPratoMouseEntered
        // TODO add your handling code here:
        jButtonAddPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ADICIONAR 2.png")));
    }//GEN-LAST:event_jButtonAddPratoMouseEntered

    private void jButtonAddPratoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddPratoMouseExited
        // TODO add your handling code here:
        jButtonAddPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ADICIONAR.png")));
    }//GEN-LAST:event_jButtonAddPratoMouseExited

    private void jButtonAddSobremesaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddSobremesaMouseEntered
        // TODO add your handling code here:
        jButtonAddSobremesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ADICIONAR 2.png")));
    }//GEN-LAST:event_jButtonAddSobremesaMouseEntered

    private void jButtonAddSobremesaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddSobremesaMouseExited
        // TODO add your handling code here:
        jButtonAddSobremesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ADICIONAR.png")));
    }//GEN-LAST:event_jButtonAddSobremesaMouseExited

    private void jButtonAddBebidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddBebidaMouseEntered
        // TODO add your handling code here:
        jButtonAddBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ADICIONAR 2.png")));
    }//GEN-LAST:event_jButtonAddBebidaMouseEntered

    private void jButtonAddBebidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddBebidaMouseExited
        // TODO add your handling code here:
        jButtonAddBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ADICIONAR.png")));
    }//GEN-LAST:event_jButtonAddBebidaMouseExited

    private void jButtonFinalizarPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFinalizarPedidoMouseEntered
        // TODO add your handling code here:
        jButtonFinalizarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO FINALIZAR PEDIDO 2.png")));
    }//GEN-LAST:event_jButtonFinalizarPedidoMouseEntered

    private void jButtonFinalizarPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFinalizarPedidoMouseExited
        // TODO add your handling code here:
        jButtonFinalizarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO FINALIZAR PEDIDO.png")));
    }//GEN-LAST:event_jButtonFinalizarPedidoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new TelaCadastroPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBebida;
    private javax.swing.JButton jButtonAddPrato;
    private javax.swing.JButton jButtonAddSobremesa;
    private javax.swing.JButton jButtonFinalizarPedido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableBebida;
    private javax.swing.JTable jTablePrato;
    private javax.swing.JTable jTableSobremesa;
    // End of variables declaration//GEN-END:variables
}
