/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controle.ControleAlterarUsuario;
import Entidade.Pessoa;
import java.util.ArrayList;

/**
 *
 * @author Samsung
 */
public class TelaAlterarUsuario extends javax.swing.JFrame {
    private ArrayList erro = new ArrayList();
    private String nome;
    private String login;
    private String senha;
    private String perfil;
    
    private String nomeAltera;
    private String loginAltera;
    private String senhaAltera;
    private String perfilAltera;
    /**
     * Creates new form TelaAlterarUsuario
     */
    public TelaAlterarUsuario(Pessoa p, Pessoa p1) {
        initComponents();
        nome = p.getNomePessoa();
        login = p.getLoginPessoa();
        senha = p.getSenhaPessoa();
        perfil = p.getPerfilPessoa();
        
        jTextFieldNome.setText(p1.getNomePessoa());
        jTextFieldLogin.setText(p1.getLoginPessoa());
        jComboBoxPerfil.setSelectedItem(p.getPerfilPessoa());
        jPasswordFieldSenha.setText(p1.getSenhaPessoa());
        
        nomeAltera = p1.getNomePessoa();
        loginAltera = p1.getLoginPessoa();
        senhaAltera = p1.getSenhaPessoa();
        perfilAltera = p1.getPerfilPessoa();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelPerfilU = new javax.swing.JLabel();
        jButtonAlterar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        NomeCompleto = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        LLogin = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jComboBoxPerfil = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/perfeito.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 430, 120, 70));

        jLabelPerfilU.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabelPerfilU.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilU.setText("Perfil do Novo Usuário:");
        getContentPane().add(jLabelPerfilU, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ALTERAR.png"))); // NOI18N
        jButtonAlterar.setBorder(null);
        jButtonAlterar.setContentAreaFilled(false);
        jButtonAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAlterarMouseExited(evt);
            }
        });
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 200, 40));

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png"))); // NOI18N
        jButtonVoltar.setBorder(null);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseExited(evt);
            }
        });
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 200, 40));

        Titulo.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("ALTERAR USUÁRIO");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 150, -1));

        NomeCompleto.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        NomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        NomeCompleto.setText("Nome Completo:");
        getContentPane().add(NomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jTextFieldNome.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 400, 30));

        LLogin.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        LLogin.setForeground(new java.awt.Color(255, 255, 255));
        LLogin.setText("Login:");
        getContentPane().add(LLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jTextFieldLogin.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 400, 30));

        jLabelSenha.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jPasswordFieldSenha.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 400, 30));

        jComboBoxPerfil.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jComboBoxPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Administrador", "Caixa", "Garçom", "Cozinha" }));
        getContentPane().add(jComboBoxPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 400, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TAMANHO CERTO.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldNome.getText();
        String login = jTextFieldLogin.getText();
        String senha = jPasswordFieldSenha.getText();
        String perfil = String.valueOf(jComboBoxPerfil.getSelectedItem());

        Pessoa p = new Pessoa(null, nomeAltera, loginAltera, perfilAltera, senhaAltera);
        p = Modelos.ModelPessoa.getInstance().obterPessoaPesquisa(p);
        Pessoa p1 = new Pessoa(p.getIdPessoa(), nome, login, perfil, senha);
        
//        System.err.println(p1);

        Controle.ControleAlterarUsuario Controle = new ControleAlterarUsuario();
        erro = Controle.validaAltDadosPessoa(p1);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaAdministrador(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlterarMouseExited
        // TODO add your handling code here:
        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ALTERAR.png")));
    }//GEN-LAST:event_jButtonAlterarMouseExited

    private void jButtonAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlterarMouseEntered
        // TODO add your handling code here:
        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ALTERAR 2.png")));
    }//GEN-LAST:event_jButtonAlterarMouseEntered

    private void jButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseEntered
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR 2.png")));
    }//GEN-LAST:event_jButtonVoltarMouseEntered

    private void jButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseExited
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png")));
    }//GEN-LAST:event_jButtonVoltarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new TelaAlterarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LLogin;
    private javax.swing.JLabel NomeCompleto;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPerfilU;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
