/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controle.ControleInserirUsuario;
import Entidade.Pessoa;
import java.util.ArrayList;

/**
 *
 * @author AndrheiHenrique
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {
    
    private ArrayList erro = new ArrayList();
    private String nome;
    private String login;
    private String senha;
    private String perfil;
    
    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroUsuario(Pessoa p) {
        initComponents();
        nome = p.getNomePessoa();
        login = p.getLoginPessoa();
        senha = p.getSenhaPessoa();
        perfil = p.getPerfilPessoa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        NomeCompleto = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        LLogin = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jComboBoxPerfil = new javax.swing.JComboBox<>();
        jLabelPerfilU = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(370, 250));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/perfeito.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 430, 130, 70));

        Titulo.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("CADASTRAR NOVO USUÁRIO");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 200, -1));

        NomeCompleto.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        NomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        NomeCompleto.setText("Nome Completo:");
        getContentPane().add(NomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jTextFieldNome.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 380, 30));

        LLogin.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        LLogin.setForeground(new java.awt.Color(255, 255, 255));
        LLogin.setText("Login:");
        getContentPane().add(LLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jTextFieldLogin.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 380, 30));

        jLabelSenha.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        jPasswordFieldSenha.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        getContentPane().add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 380, 30));

        jComboBoxPerfil.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jComboBoxPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Administrador", "Caixa", "Garçom", "Cozinha" }));
        getContentPane().add(jComboBoxPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 380, 30));

        jLabelPerfilU.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabelPerfilU.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfilU.setText("Perfil do Novo Usuário:");
        getContentPane().add(jLabelPerfilU, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, 20));

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO SALVAR.png"))); // NOI18N
        jButtonSalvar.setBorder(null);
        jButtonSalvar.setContentAreaFilled(false);
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseExited(evt);
            }
        });
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 200, 40));

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png"))); // NOI18N
        jButtonVoltar.setBorder(null);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseExited(evt);
            }
        });
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TAMANHO CERTO.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldNome.getText();
        String login = jTextFieldLogin.getText();
        String senha = jPasswordFieldSenha.getText();
        String perfil = String.valueOf(jComboBoxPerfil.getSelectedItem());
        
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        
        Controle.ControleInserirUsuario Controle = new ControleInserirUsuario();
        erro = Controle.validaDadosPessoa(p);
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaAdministrador(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseEntered
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR 2.png")));
    }//GEN-LAST:event_jButtonVoltarMouseEntered

    private void jButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseExited
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png")));
    }//GEN-LAST:event_jButtonVoltarMouseExited

    private void jButtonSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseEntered
        // TODO add your handling code here:
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO SALVAR 2.png")));
    }//GEN-LAST:event_jButtonSalvarMouseEntered

    private void jButtonSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseExited
        // TODO add your handling code here:
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO SALVAR.png")));
    }//GEN-LAST:event_jButtonSalvarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new TelaCadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LLogin;
    private javax.swing.JLabel NomeCompleto;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPerfilU;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
