/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Entidade.Pessoa;

/**
 *
 * @author AndrheiHenrique
 */
public class TelaAdministrador extends javax.swing.JFrame {

    private String nome;
    private String login;
    private String senha;
    private String perfil;
    /**
     * Creates new form TelaAdministrador
     */
    public TelaAdministrador(Pessoa p) {
        initComponents();
        jLabelNomeUsuario1.setText(p.getPerfilPessoa()+": "+p.getNomePessoa());
        nome = p.getNomePessoa();
        login = p.getLoginPessoa();
        senha = p.getSenhaPessoa();
        perfil = p.getPerfilPessoa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jMenuItem2 = new javax.swing.JMenuItem();
        jButtonCadastroUsuario = new javax.swing.JButton();
        jLabelNomeUsuario1 = new javax.swing.JLabel();
        jButtonCadastrarPrato = new javax.swing.JButton();
        jButtonCadastrarBebida = new javax.swing.JButton();
        jButtonCadastrarSobremesas = new javax.swing.JButton();
        jButtonSobremesas = new javax.swing.JButton();
        jButtonBebidas = new javax.swing.JButton();
        jButtonPratos = new javax.swing.JButton();
        jButtonUsuario = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemControleMensal = new javax.swing.JMenuItem();

        jLabel3.setText("jLabel3");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CADASTRAR NOVO USUARIO2.png"))); // NOI18N
        jButtonCadastroUsuario.setBorder(null);
        jButtonCadastroUsuario.setContentAreaFilled(false);
        jButtonCadastroUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCadastroUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCadastroUsuarioMouseExited(evt);
            }
        });
        jButtonCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 200, 40));

        jLabelNomeUsuario1.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabelNomeUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelNomeUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 460, 30));

        jButtonCadastrarPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CADASTRAR PRATO.png"))); // NOI18N
        jButtonCadastrarPrato.setBorder(null);
        jButtonCadastrarPrato.setContentAreaFilled(false);
        jButtonCadastrarPrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCadastrarPratoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCadastrarPratoMouseExited(evt);
            }
        });
        jButtonCadastrarPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarPratoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrarPrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 200, 40));

        jButtonCadastrarBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CADASTRAR BEBIDA.png"))); // NOI18N
        jButtonCadastrarBebida.setBorder(null);
        jButtonCadastrarBebida.setContentAreaFilled(false);
        jButtonCadastrarBebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCadastrarBebidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCadastrarBebidaMouseExited(evt);
            }
        });
        jButtonCadastrarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarBebidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrarBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 200, 40));

        jButtonCadastrarSobremesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO CADASTRAR SOBREMESA.png"))); // NOI18N
        jButtonCadastrarSobremesas.setBorder(null);
        jButtonCadastrarSobremesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCadastrarSobremesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCadastrarSobremesasMouseExited(evt);
            }
        });
        jButtonCadastrarSobremesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarSobremesasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrarSobremesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 200, 40));

        jButtonSobremesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SOBREMESAS.png"))); // NOI18N
        jButtonSobremesas.setBorder(null);
        jButtonSobremesas.setContentAreaFilled(false);
        jButtonSobremesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSobremesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSobremesasMouseExited(evt);
            }
        });
        jButtonSobremesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobremesasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSobremesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 200, 40));

        jButtonBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BEBIDAS.png"))); // NOI18N
        jButtonBebidas.setBorder(null);
        jButtonBebidas.setBorderPainted(false);
        jButtonBebidas.setContentAreaFilled(false);
        jButtonBebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBebidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonBebidasMouseExited(evt);
            }
        });
        jButtonBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBebidasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 200, 40));

        jButtonPratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PRATOS.png"))); // NOI18N
        jButtonPratos.setBorder(null);
        jButtonPratos.setContentAreaFilled(false);
        jButtonPratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPratosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPratosMouseExited(evt);
            }
        });
        jButtonPratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPratosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 200, 40));

        jButtonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/USUARIOS.png"))); // NOI18N
        jButtonUsuario.setBorder(null);
        jButtonUsuario.setContentAreaFilled(false);
        jButtonUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUsuarioMouseExited(evt);
            }
        });
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 200, 40));

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png"))); // NOI18N
        jButtonVoltar.setBorder(null);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseExited(evt);
            }
        });
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 200, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sobremesa.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 120));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bebidasss.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 750, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Wallpaper Prato.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 750, 120));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TAMANHO CERTO.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 750, 120));

        jMenu1.setText("Controles");

        jMenuItemControleMensal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemControleMensal.setText("Controle Mensal");
        jMenuItemControleMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemControleMensalActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemControleMensal);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioMouseEntered
        // TODO add your handling code here:
        jButtonCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CADASTRAR NOVO USUARIO.png")));
    }//GEN-LAST:event_jButtonCadastroUsuarioMouseEntered

    private void jButtonCadastroUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioMouseExited
        // TODO add your handling code here:
        jButtonCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CADASTRAR NOVO USUARIO2.png")));
    }//GEN-LAST:event_jButtonCadastroUsuarioMouseExited

    private void jButtonCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaCadastroUsuario(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCadastroUsuarioActionPerformed

    private void jButtonCadastrarPratoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarPratoMouseEntered
        // TODO add your handling code here:
        jButtonCadastrarPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CADASTRAR PRATO 2.png")));
    }//GEN-LAST:event_jButtonCadastrarPratoMouseEntered

    private void jButtonCadastrarPratoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarPratoMouseExited
        // TODO add your handling code here:
        jButtonCadastrarPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CADASTRAR PRATO.png")));
    }//GEN-LAST:event_jButtonCadastrarPratoMouseExited

    private void jButtonCadastrarPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarPratoActionPerformed
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaCadastroPrato(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCadastrarPratoActionPerformed

    private void jButtonCadastrarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarBebidaActionPerformed
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaCadastroBebida(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCadastrarBebidaActionPerformed

    private void jButtonCadastrarSobremesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarSobremesasActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaCadastroSobremesa(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCadastrarSobremesasActionPerformed

    private void jButtonSobremesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSobremesasMouseEntered
        // TODO add your handling code here:
        jButtonSobremesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SOBREMESAS2.png")));
    }//GEN-LAST:event_jButtonSobremesasMouseEntered

    private void jButtonSobremesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSobremesasMouseExited
        // TODO add your handling code here:
        jButtonSobremesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SOBREMESAS.png")));
    }//GEN-LAST:event_jButtonSobremesasMouseExited

    private void jButtonSobremesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobremesasActionPerformed
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaSobremesa(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSobremesasActionPerformed

    private void jButtonBebidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBebidasMouseEntered
        // TODO add your handling code here:
        jButtonBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BEBIDAS2.png")));
    }//GEN-LAST:event_jButtonBebidasMouseEntered

    private void jButtonBebidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBebidasMouseExited
        // TODO add your handling code here:
        jButtonBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BEBIDAS.png")));
    }//GEN-LAST:event_jButtonBebidasMouseExited

    private void jButtonBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBebidasActionPerformed
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaBebida(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBebidasActionPerformed

    private void jButtonPratosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPratosMouseEntered
        // TODO add your handling code here:
        jButtonPratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PRATOS2.png")));
    }//GEN-LAST:event_jButtonPratosMouseEntered

    private void jButtonPratosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPratosMouseExited
        // TODO add your handling code here:
        jButtonPratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PRATOS.png")));
    }//GEN-LAST:event_jButtonPratosMouseExited

    private void jButtonPratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPratosActionPerformed
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaPrato(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPratosActionPerformed

    private void jButtonUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUsuarioMouseEntered
        // TODO add your handling code here:
        jButtonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/USUARIOS2.png")));
    }//GEN-LAST:event_jButtonUsuarioMouseEntered

    private void jButtonUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUsuarioMouseExited
        // TODO add your handling code here:
        jButtonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/USUARIOS.png")));
    }//GEN-LAST:event_jButtonUsuarioMouseExited

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaUsuario(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonCadastrarBebidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarBebidaMouseEntered
        // TODO add your handling code here:
        jButtonCadastrarBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CADASTRAR BEBIDA2.png")));
    }//GEN-LAST:event_jButtonCadastrarBebidaMouseEntered

    private void jButtonCadastrarBebidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarBebidaMouseExited
        // TODO add your handling code here:
        jButtonCadastrarBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CADASTRAR BEBIDA.png")));
    }//GEN-LAST:event_jButtonCadastrarBebidaMouseExited

    private void jButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseEntered
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR 2.png")));
    }//GEN-LAST:event_jButtonVoltarMouseEntered

    private void jButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseExited
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png")));
    }//GEN-LAST:event_jButtonVoltarMouseExited

    private void jButtonCadastrarSobremesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarSobremesasMouseEntered
        // TODO add your handling code here:
        jButtonCadastrarSobremesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO CADASTRAR SOBREMESA 2.png")));
    }//GEN-LAST:event_jButtonCadastrarSobremesasMouseEntered

    private void jButtonCadastrarSobremesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarSobremesasMouseExited
        // TODO add your handling code here:
        jButtonCadastrarSobremesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO CADASTRAR SOBREMESA.png")));
    }//GEN-LAST:event_jButtonCadastrarSobremesasMouseExited

    private void jMenuItemControleMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemControleMensalActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaControleMensal(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemControleMensalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new TelaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBebidas;
    private javax.swing.JButton jButtonCadastrarBebida;
    private javax.swing.JButton jButtonCadastrarPrato;
    private javax.swing.JButton jButtonCadastrarSobremesas;
    private javax.swing.JButton jButtonCadastroUsuario;
    private javax.swing.JButton jButtonPratos;
    private javax.swing.JButton jButtonSobremesas;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelNomeUsuario1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemControleMensal;
    // End of variables declaration//GEN-END:variables
}
