/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Entidade.Pedido;
import Entidade.Pessoa;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samsung
 */
public class TelaControleDiario extends javax.swing.JFrame {

    private ArrayList<Pedido> lista = new ArrayList();
    private String nome;
    private String login;
    private String senha;
    private String perfil;
    private NumberFormat formatter = new DecimalFormat("0.00");
    
    /**
     * Creates new form TelaControleCaixa
     */
    public TelaControleDiario(Pessoa p) {
        initComponents();
        nome = p.getNomePessoa();
        login = p.getLoginPessoa();
        senha = p.getSenhaPessoa();
        perfil = p.getPerfilPessoa();
        construirTabela();
    }
    private void construirTabela(){
        lista = Modelos.ModelPedido.getInstance().obterPedidoControle();
        
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Nome");
        modelo.addColumn("Nome Garçom");
        modelo.addColumn("Tamanho");
        modelo.addColumn("Preço");

        if (lista.isEmpty()) {
            modelo.addRow(new String[]{"Sem dados",
                        null,
                        null,
                        null,});
        }
        
        for (int i = 0; i < lista.size(); i++) {
            Pedido p = lista.get(i);
            modelo.addRow(new String[]{
                        p.getNomePedido(),
                        p.getNomeGarcomPedido()+"",
                        p.getTamanhoPedido()+"",
                        "R$ "+formatter.format(p.getPrecoPedido())+ "",});
        }

        jTableControles.setModel(modelo);
    }

    private String getDataHora() {
	DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
	Date date = new Date();
	return dateFormat.format(date);
}
    
    private float getValorTotal(){
        float vTototal = 0;
        for (int i = 0; i < lista.size(); i++) {
            Pedido p = lista.get(i);
            
            vTototal = vTototal + p.getPrecoPedido();
        }
        return vTototal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableControles = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();
        jButtonFecharCaixa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/perfeito.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 430, 120, 70));

        jTableControles.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jTableControles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableControles);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 700, 400));

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png"))); // NOI18N
        jButtonVoltar.setBorder(null);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseExited(evt);
            }
        });
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 200, 40));

        jButtonFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO FECHAR CAIXA.png"))); // NOI18N
        jButtonFecharCaixa.setBorder(null);
        jButtonFecharCaixa.setContentAreaFilled(false);
        jButtonFecharCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonFecharCaixaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonFecharCaixaMouseExited(evt);
            }
        });
        jButtonFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharCaixaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFecharCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 430, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TAMANHO CERTO.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseEntered
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR 2.png")));
    }//GEN-LAST:event_jButtonVoltarMouseEntered

    private void jButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseExited
        // TODO add your handling code here:
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png")));
    }//GEN-LAST:event_jButtonVoltarMouseExited

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa(nome, login, perfil, senha);
        new TelaCaixa(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCaixaActionPerformed
        // TODO add your handling code here:
        String data = getDataHora();
        float vTotal = getValorTotal();
        int qtdVendas = lista.size();
        
        try {
            Modelos.ModelControles.getInstance().transferirCotroleDpM(data, vTotal, qtdVendas);
            Modelos.ModelPedido.getInstance().limpaTabelaPedido();
            JOptionPane.showMessageDialog(null, "Caixa fechado com sucesso!!!");
            construirTabela();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaControleDiario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaControleDiario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFecharCaixaActionPerformed

    private void jButtonFecharCaixaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFecharCaixaMouseEntered
        // TODO add your handling code here:
        jButtonFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO FECHAR CAIXA 2.png")));
    }//GEN-LAST:event_jButtonFecharCaixaMouseEntered

    private void jButtonFecharCaixaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFecharCaixaMouseExited
        // TODO add your handling code here:
        jButtonFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO FECHAR CAIXA.png")));
    }//GEN-LAST:event_jButtonFecharCaixaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaControleDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaControleDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaControleDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaControleDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new TelaControleDiario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFecharCaixa;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableControles;
    // End of variables declaration//GEN-END:variables
}
