/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Entidade.Pedido;
import Entidade.Pessoa;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndrheiHenrique
 */
public class TelaCozinha extends javax.swing.JFrame {

    private ArrayList<Pedido> listaPedido = new ArrayList();
    /**
     * Creates new form TelaCozinha
     */
    public TelaCozinha(Pessoa p) {
        initComponents();
        
        jLabelNomeUsuario.setText(p.getPerfilPessoa()+": "+p.getNomePessoa());
        construirTabela();
        jButtonPedidoFinalizado.setEnabled(false);        
    }
    
    private void construirTabela(){
    ArrayList<Pedido> lista = Modelos.ModelPedido.getInstance().obterPedidoCozinha();
        
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Nome");
        modelo.addColumn("Tamanho");
        modelo.addColumn("Mesa");

        if (lista.isEmpty()) {
            modelo.addRow(new String[]{"Sem dados",
                        null,
                        null,});
        }
        
        for (int i = 0; i < lista.size(); i++) {
            Pedido p = lista.get(i);
            modelo.addRow(new String[]{
                        p.getNomePedido(),
                        p.getTamanhoPedido()+"",
                        p.getMesaPedido()+ "",});
        }

        jTable1.setModel(modelo);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAtualizarPedido = new javax.swing.JButton();
        jButtonPedidoFinalizado = new javax.swing.JButton();
        jButtonVoltar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNomeUsuario.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabelNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 710, 390));

        jButtonAtualizarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ATUALIZAR PEDIDO.png"))); // NOI18N
        jButtonAtualizarPedido.setBorder(null);
        jButtonAtualizarPedido.setContentAreaFilled(false);
        jButtonAtualizarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAtualizarPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAtualizarPedidoMouseExited(evt);
            }
        });
        jButtonAtualizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAtualizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 200, 40));

        jButtonPedidoFinalizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO PEDIDO FINALIZADO.png"))); // NOI18N
        jButtonPedidoFinalizado.setBorder(null);
        jButtonPedidoFinalizado.setContentAreaFilled(false);
        jButtonPedidoFinalizado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPedidoFinalizadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPedidoFinalizadoMouseExited(evt);
            }
        });
        jButtonPedidoFinalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedidoFinalizadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPedidoFinalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 200, 40));

        jButtonVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png"))); // NOI18N
        jButtonVoltar1.setBorder(null);
        jButtonVoltar1.setContentAreaFilled(false);
        jButtonVoltar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltar1MouseExited(evt);
            }
        });
        jButtonVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVoltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TAMANHO CERTO.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarPedidoActionPerformed
        // TODO add your handling code here:
        construirTabela();
    }//GEN-LAST:event_jButtonAtualizarPedidoActionPerformed

    private void jButtonPedidoFinalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedidoFinalizadoActionPerformed
        // TODO add your handling code here:
        int linha = jTable1.getSelectedRow();
        int mesa =Integer.valueOf(String.valueOf(jTable1.getValueAt(linha, 2)));
        String nome =String.valueOf(jTable1.getValueAt(linha, 0));
        
        listaPedido = Modelos.ModelPedido.getInstance().obterAlteraPedido(mesa,nome);
        
        Pedido p = listaPedido.get(0);
        
        Modelos.ModelPedido.getInstance().alteraPedidoRealizado(p);
        construirTabela();
        jButtonPedidoFinalizado.setEnabled(false);
    }//GEN-LAST:event_jButtonPedidoFinalizadoActionPerformed

    private void jButtonVoltar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltar1MouseEntered
        // TODO add your handling code here:
        jButtonVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR 2.png")));
    }//GEN-LAST:event_jButtonVoltar1MouseEntered

    private void jButtonVoltar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltar1MouseExited
        // TODO add your handling code here:
        jButtonVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO VOLTAR.png")));
    }//GEN-LAST:event_jButtonVoltar1MouseExited

    private void jButtonVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_jButtonVoltar1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jButtonPedidoFinalizado.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonAtualizarPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtualizarPedidoMouseEntered
        // TODO add your handling code here:
        jButtonAtualizarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ATUALIZAR PEDIDO 2.png")));
    }//GEN-LAST:event_jButtonAtualizarPedidoMouseEntered

    private void jButtonAtualizarPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtualizarPedidoMouseExited
        // TODO add your handling code here:
        jButtonAtualizarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO ATUALIZAR PEDIDO.png")));
    }//GEN-LAST:event_jButtonAtualizarPedidoMouseExited

    private void jButtonPedidoFinalizadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPedidoFinalizadoMouseEntered
        // TODO add your handling code here:
        jButtonPedidoFinalizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO PEDIDO FINALIZADO 2.png")));
    }//GEN-LAST:event_jButtonPedidoFinalizadoMouseEntered

    private void jButtonPedidoFinalizadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPedidoFinalizadoMouseExited
        // TODO add your handling code here:
        jButtonPedidoFinalizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BOTÃO PEDIDO FINALIZADO.png")));
    }//GEN-LAST:event_jButtonPedidoFinalizadoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new TelaCozinha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarPedido;
    private javax.swing.JButton jButtonPedidoFinalizado;
    private javax.swing.JButton jButtonVoltar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
